---
server.port: ${PORT:${SERVER_PORT:0}}

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely


---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog

---
spring:
  profiles: cold-noun
words: 0icicle,0refrigerator,0blizzard,0snowball

---
spring:
  profiles: subject
words: I,You,He,She,It

---
spring:
  profiles: verb
words: ran,knew,had,saw,bought
